# Generated by Django 5.2.8 on 2025-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('teknoloji', models.CharField(max_length=50)),
                ('resim', models.ImageField(blank=True, upload_to='projeler/')),
            ],
        ),
    ]
