# Generated by Django 5.2.8 on 2025-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
