# Generated by Django 5.2.8 on 2025-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_proje_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('ozet', models.TextField()),
                ('profil_resmi', models.ImageField(blank=True, upload_to='profil/')),
            ],
            options={
                'verbose_name_plural': 'Hakkımda Sayfası (Sadece 1 Kayıt Girin)',
            },
        ),
    ]
