# Generated by Django 5.2.8 on 2025-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_hakkimda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='teknoloji',
            field=models.CharField(help_text='Örn: Python Django Bootstrap', max_length=150),
        ),
    ]
